### ISSUE TITLE
Enum types are messed up

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ViZDoom.jl#7]
According to the error messages here https://travis-ci.org/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/jobs/563906398#L3192

The enum of `ViZDoom.RES_160X120` seems to be of the wrong type. After testing, I find that, with CxxWrap@v0.8.1, everything is OK and the value of `ViZDoom.RES_160X120` is of  `ViZDoom.ScreenResolution(0x00000000)`, but with with CxxWrap@v0.8.2, the DataType is very weird.

In fact, I find that most of the enum types are of strange data types, like `(Tuple, )`, `Error showing value of type Tuple{Core.Compiler.OneTo{Int64}}`.

**Comment by Islandman93** [comment]
Fixed by #10
